##########
# for the 24 chromosomes generated by
# freebayes_parallel_by_chromosome.sh

# there are now 24 vcf files, each of which needs to be filtered.

parallel --dryrun "SNPfilter.sh {}" ::: *.vcf

# then concatenate all vcf files in proper order
# but skip first chromosome, all.freebayes.Chromosome_2.vcf

ls *SNPs.filtered.final.recode.vcf |sort -k2,2h -t '_' | sed 1d > vcf_list.txt


# now join only keeping the header for the first chromosome
{ xargs cat < vcf_list.txt ; } | awk '{if ($1 !~ /^#/) print $0}' | \
cat all.freebayes.Chromosome_2.SNPs.filtered.final.recode.vcf - > all.freebayes.chrom2_25.SNPs.filtered.final.recode.vcf
